# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CS506' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CS506
	# TODO: Clean this mess later
	pod 'Firebase/Core'
	pod 'Firebase/AdMob'
	pod 'Firebase/Analytics'
	pod 'Firebase/Auth'
	pod 'Firebase/Crash'
	pod 'Firebase/Database'
	pod 'Firebase/DynamicLinks'
#	pod 'Firebase/Invites'
	pod 'Firebase/Messaging'
	pod 'Firebase/Performance'
	pod 'Firebase/RemoteConfig'
	pod 'Firebase/Storage'
  target 'CS506Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CS506UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
